### ISSUE TITLE
2021 New Year release

### ISSUE THREAD

**Issue by Profpatsch** [flexibeast/s6-man-pages#1]
There are a few (breaking) changes in the tools and I’d assume the documentation has been updated in a nontrivial fashion.

https://www.mail-archive.com/skaware@list.skarnet.org/msg01510.html

**Comment by flexibeast** [comment]
Yes indeed! i've actually just started work on this today, but i can't make any promises as to when the update will be completed; unfortunately i'm currently dealing with even more health issues than usual, so i'll gradually progress the update as i find the resources to do so.

**Comment by flexibeast** [comment]
Updated for s6 2.10.0.0, tag created: https://github.com/flexibeast/s6-man-pages/releases/tag/v2.10.0.0.1
