### ISSUE TITLE
mdoc is man pages

### ISSUE THREAD

**Issue by causal-agent** [flexibeast/s6-man-pages#3]
mdoc files already are man pages and can be installed as-is and rendered by either groff or mandoc. There's no need for the preprocessing step of converting mdoc(7) to man(7), which loses semantic information.

**Comment by kdkasad** [comment]
I agree with this. In the [PKGBUILD for the AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=s6-man-pages-git), I skipped the Makefile entirely because it has the unnecessary conversion step.

**Comment by flexibeast** [comment]
My apologies, and thanks for the heads-up! i've now fixed this and added a new tag (and have done the same in the s6-networking-man-pages repo).
