### ISSUE TITLE
Section of the manual

### ISSUE THREAD

**Issue by janicez** [flexibeast/s6-man-pages#6]
Shouldn't many section 1 s6 manual pages be in section 8, as they are first-and-foremost administrative in nature? I understand they do not require administrative access, but many section 8 commands do not either.

**Comment by flexibeast** [comment]
Good point. i've got a lot on my plate at the moment, so i might not be able to get to this for a couple of weeks; but you're welcome to submit a PR sooner if you're feeling enthusiastic. :-)

**Comment by flexibeast** [comment]
Update: Now that i've updated the skaware man-page repos, i'm hoping to address this issue soon. :-)

**Comment by flexibeast** [comment]
All the `.1` pages are now `.8`; there weren't any that i felt should be kept as `.1`. All this applies to the [s6-networking-man-pages](https://github.com/flexibeast/s6-networking-man-pages) repo as well; but i kept all the `.1` pages in [execline-man-pages](https://github.com/flexibeast/execline-man-pages/) as-is.

Does all that seem okay?

**Comment by janicez** [comment]
If I disagree with your judgment I can always fork the project and it's no harm, no foul.

I'd suggest maybe client apps in s6-n-m-p would be .1, but otherwise I think your judgment is sound. I'm sorry I couldn't help more directly.

On 29 September 2021 02:44:34 UTC, Alexis ***@***.***> wrote:
>All the `.1` pages are now `.8`; there weren't any that i felt should be kept as `.1`. All this applies to the [s6-networking-man-pages](https://github.com/flexibeast/s6-networking-man-pages) repo as well; but i kept all the `.1` pages in [execline-man-pages](https://github.com/flexibeast/execline-man-pages/) as-is.
>
>Does all that seem okay?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/flexibeast/s6-man-pages/issues/6#issuecomment-929778183
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by flexibeast** [comment]
> I'd suggest maybe client apps in s6-n-m-p would be .1

Yeah, i'd considered that myself .... In the end my feeling was that the s6-networking clients:

* `s6-ident-client`
* `s6-sntpclock`
* `s6-taiclock`
* `s6-tcpclient`
* `s6-tlsc`
* `s6-tlsc-io`
* `s6-tlsclient`
* `s6-ucspitlsc`
 
are perhaps most likely to be utilised in a system administration context. So i think i'll leave things as-is for now; but if anyone else expresses a preference for these pages to be in section 1, i'll happily move them. 

> I'm sorry I couldn't help more directly.

No worries! Thanks for the constructive feedback. :-)
